### ISSUE TITLE
配置文件步骤报错

### ISSUE THREAD

**Issue by glkwhr** [TRPGEngine/Server#113]
按照README中的步骤进行到“配置文件“这一步。按照示例内容创建了`local.js`文件：
```js
module.exports = {
  db: {
    database: 'trpg',
    username: 'root',
    password: 'root',  // 改成了本地mysql root user的密码
    options: {
      host: 'localhost',
      dialect: 'mysql',
    },
  },
  jwt: {
    secret: 'any string',
  },
  redisUrl: 'redis://127.0.0.1:6379/8',
};
```

之后在执行`$ yarn run db:migrate:run`出现如下错误：
```
$ yarn run db:migrate:run
yarn run v1.22.10
$ node ./cli.js db run-migrate

/home/glkwhr/Documents/Codes/trpg_engine/Server/db/models.js:4
  sequelize: app.storage.db,
                         ^
TypeError: Cannot read property 'db' of null
    at Object.<anonymous> (/home/glkwhr/Documents/Codes/trpg_engine/Server/db/models.js:4:26)
    at Module._compile (node:internal/modules/cjs/loader:1109:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1138:10)
    at Module.load (node:internal/modules/cjs/loader:989:32)
    at Function.Module._load (node:internal/modules/cjs/loader:829:14)
    at Module.require (node:internal/modules/cjs/loader:1013:19)
    at require (node:internal/modules/cjs/helpers:93:18)
    at Object.<anonymous> (/home/glkwhr/Documents/Codes/trpg_engine/Server/node_modules/sequelize-auto-migrations/bin/runmigration.js:60:19)
    at Module._compile (node:internal/modules/cjs/loader:1109:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1138:10)
    at Module.load (node:internal/modules/cjs/loader:989:32)
    at Function.Module._load (node:internal/modules/cjs/loader:829:14)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12)
    at node:internal/main/run_main_module:17:47
正在关闭应用...
Done in 21.53s.
```

请问下有没有头绪这是个什么情况？

**Comment by moonrailgun** [comment]
Hi, 很高兴收到您的问题。这个问题看起来是因为应用的数据库相关服务没有正确启动导致的，为了重现该问题，希望提供以下内容:

- node版本
- TRPGEngine/Server 的 版本hash
- 系统版本

因为 `TRPG Engine` 长期使用 ci 工具来保证代码的可靠性, 建议您优先查找一下是否是配置或者环境有什么问题，如果找到了解决方案，可以分享一下。

如果实在无法解决，可以尝试使用docker部署的方式进行部署 [相关文档](https://trpgdoc.moonrailgun.com/docs/selfhost/selfhost)

**Comment by glkwhr** [comment]
谢谢回复！

node版本: v16.2.0
commit hash: a1b3d83b8aeb8056e6a6bbedea587ea4fdf3277c
OS: Linux ubuntu 5.4.0-73-generic #82-Ubuntu SMP Wed Apr 14 17:39:42 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

redis-server和mysql-server都在运行。

请问有可能是因为创建的`local.js`中的配置不全吗？我只放了示例内容（mysql用户名密码和redis地址）。

我觉得有可能是配置或者环境的问题，但根据错误信息并不是很明确研究的方向。。

**Comment by moonrailgun** [comment]
@glkwhr 感谢你发现的问题，该问题已经在master分支上修复了该问题，请拉取一下代码后再试

**Comment by glkwhr** [comment]
> @glkwhr 感谢你发现的问题，该问题已经在master分支上修复了该问题，请拉取一下代码后再试

多谢修复！之前那个错误已经解决，不过现在有另一个问题：
```
{ SequelizeConnectionError: Client does not support authentication protocol requested by server; consider upgrading MySQL client
    at Promise.tap.then.catch.err (/home/glkwhr/Documents/Codes/trpg_engine/Server/node_modules/sequelize/lib/dialects/mysql/connection-manager.js:133:19)
    at tryCatcher (/home/glkwhr/Documents/Codes/trpg_engine/Server/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/glkwhr/Documents/Codes/trpg_engine/Server/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/home/glkwhr/Documents/Codes/trpg_engine/Server/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/home/glkwhr/Documents/Codes/trpg_engine/Server/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/home/glkwhr/Documents/Codes/trpg_engine/Server/node_modules/bluebird/js/release/promise.js:725:18)
    at _drainQueueStep (/home/glkwhr/Documents/Codes/trpg_engine/Server/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/home/glkwhr/Documents/Codes/trpg_engine/Server/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/home/glkwhr/Documents/Codes/trpg_engine/Server/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/glkwhr/Documents/Codes/trpg_engine/Server/node_modules/bluebird/js/release/async.js:15:14)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
    at process.topLevelDomainCallback (domain.js:126:23)
  name: 'SequelizeConnectionError',
  parent:
   { Error: Client does not support authentication protocol requested by server; consider upgrading MySQL client
       at Packet.asError (/home/glkwhr/Documents/Codes/trpg_engine/Server/node_modules/mysql2/lib/packets/packet.js:708:17)
       at ClientHandshake.execute (/home/glkwhr/Documents/Codes/trpg_engine/Server/node_modules/mysql2/lib/commands/command.js:28:26)
       at Connection.handlePacket (/home/glkwhr/Documents/Codes/trpg_engine/Server/node_modules/mysql2/lib/connection.js:408:32)
       at PacketParser.Connection.packetParser.p [as onPacket] (/home/glkwhr/Documents/Codes/trpg_engine/Server/node_modules/mysql2/lib/connection.js:70:12)
       at PacketParser.executeStart (/home/glkwhr/Documents/Codes/trpg_engine/Server/node_modules/mysql2/lib/packet_parser.js:75:16)
       at Socket.Connection.stream.on.data (/home/glkwhr/Documents/Codes/trpg_engine/Server/node_modules/mysql2/lib/connection.js:77:25)
       at Socket.emit (events.js:198:13)
       at Socket.EventEmitter.emit (domain.js:448:20)
       at addChunk (_stream_readable.js:288:12)
       at readableAddChunk (_stream_readable.js:269:11)
       at Socket.Readable.push (_stream_readable.js:224:10)
       at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
     code: 'ER_NOT_SUPPORTED_AUTH_MODE',
     errno: 1251,
     sqlState: '08004',
     sqlMessage:
      'Client does not support authentication protocol requested by server; consider upgrading MySQL client' },
  original:
   { Error: Client does not support authentication protocol requested by server; consider upgrading MySQL client
       at Packet.asError (/home/glkwhr/Documents/Codes/trpg_engine/Server/node_modules/mysql2/lib/packets/packet.js:708:17)
       at ClientHandshake.execute (/home/glkwhr/Documents/Codes/trpg_engine/Server/node_modules/mysql2/lib/commands/command.js:28:26)
       at Connection.handlePacket (/home/glkwhr/Documents/Codes/trpg_engine/Server/node_modules/mysql2/lib/connection.js:408:32)
       at PacketParser.Connection.packetParser.p [as onPacket] (/home/glkwhr/Documents/Codes/trpg_engine/Server/node_modules/mysql2/lib/connection.js:70:12)
       at PacketParser.executeStart (/home/glkwhr/Documents/Codes/trpg_engine/Server/node_modules/mysql2/lib/packet_parser.js:75:16)
       at Socket.Connection.stream.on.data (/home/glkwhr/Documents/Codes/trpg_engine/Server/node_modules/mysql2/lib/connection.js:77:25)
       at Socket.emit (events.js:198:13)
       at Socket.EventEmitter.emit (domain.js:448:20)
       at addChunk (_stream_readable.js:288:12)
       at readableAddChunk (_stream_readable.js:269:11)
       at Socket.Readable.push (_stream_readable.js:224:10)
       at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
     code: 'ER_NOT_SUPPORTED_AUTH_MODE',
     errno: 1251,
     sqlState: '08004',
     sqlMessage:
      'Client does not support authentication protocol requested by server; consider upgrading MySQL client' } }
[chat]加载会话列表失败
...
```
看起来问题是`Client does not support authentication protocol requested by server; consider upgrading MySQL client`

我的mysql client版本如下，不过我觉得错误信息中提到的client应该不是指这个？我直接用mysql命令可以正常访问数据库。
```
$ mysql --version
mysql  Ver 8.0.25-0ubuntu0.20.04.1 for Linux on x86_64 ((Ubuntu))
```

**Comment by glkwhr** [comment]
问题解决了：

1. mysql中用户权限问题。root user需要`$ sudo mysql -u root -p`来登陆。执行下列命令解除该限制（[参考](https://stackoverflow.com/questions/37239970/connect-to-mysql-server-without-sudo)）：
```
mysql > ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'your_password';
mysql > FLUSH PRIVILEGES;
```

2. database需要事先创建：
```
mysql> CREATE DATABASE trpg;
Query OK, 1 row affected (0.17 sec)

```

**Comment by moonrailgun** [comment]
`TRPG Engine` 是基于mysql 5.7开发的。

而Mysql在8.0的时候修改了用户鉴权的方式。

具体可以看[这篇文章](https://mysqlserverteam.com/mysql-8-0-4-new-default-authentication-plugin-caching_sha2_password/)
